#+TITLE: Peroxisomal Disorders
#+AUTHOR: Matthew Henderson, PhD, FCACB
#+DATE: \today

:PROPERTIES:
#+DRAWERS: PROPERTIES
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [presentation, smaller]
#+BEAMER_THEME: Hannover
#+BEAMER_COLOR_THEME: whale
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)
#+OPTIONS: H:2 toc:nil ^:t
#+PROPERTY: header-args:R :session *R*
#+PROPERTY: header-args :cache no
#+PROPERTY: header-args :tangle yes
#+STARTUP: beamer
#+STARTUP: overview
#+STARTUP: indent
# #+BEAMER_HEADER: \subtitle{Part 1: Maple Syrup Urine Diseas}
#+BEAMER_HEADER: \institute[NSO]{Newborn Screening Ontario | The University of Ottawa}
#+BEAMER_HEADER: \titlegraphic{\includegraphics[height=1cm,keepaspectratio]{../logos/NSO_logo.pdf}\includegraphics[height=1cm,keepaspectratio]{../logos/cheo-logo.png} \includegraphics[height=1cm,keepaspectratio]{../logos/UOlogoBW.eps}}
#+latex_header: \hypersetup{colorlinks,linkcolor=white,urlcolor=blue}
#+LaTeX_header: \usepackage{textpos}
#+LaTeX_header: \usepackage{textgreek}
#+LaTeX_header: \usepackage[version=4]{mhchem}
#+LaTeX_header: \usepackage{chemfig}
#+LaTeX_header: \usepackage{siunitx}
#+LaTeX_header: \usepackage{gensymb}
#+LaTex_HEADER: \usepackage[usenames,dvipsnames]{xcolor}
#+LaTeX_HEADER: \usepackage[T1]{fontenc}
#+LaTeX_HEADER: \usepackage{lmodern}
#+LaTeX_HEADER: \usepackage{verbatim}
#+LaTeX_HEADER: \usepackage{tikz}
#+LaTeX_HEADER: \usepackage{wasysym}
#+LaTeX_HEADER: \usetikzlibrary{shapes.geometric,arrows,decorations.pathmorphing,backgrounds,positioning,fit,petri}
:END:

#+BEGIN_EXPORT LaTeX
%\logo{\includegraphics[width=1cm,height=1cm,keepaspectratio]{../logos/NSO_logo_small.pdf}~%
%    \includegraphics[width=1cm,height=1cm,keepaspectratio]{../logos/UOlogoBW.eps}%
%}

\vspace{220pt}
\beamertemplatenavigationsymbolsempty
\setbeamertemplate{caption}[numbered]
\setbeamerfont{caption}{size=\tiny}
% \addtobeamertemplate{frametitle}{}{%
% \begin{textblock*}{100mm}(.85\textwidth,-1cm)
% \includegraphics[height=1cm,width=2cm]{cat}
% \end{textblock*}}
#+END_EXPORT 

* Peroxisomal \beta-oxidation Disorders
** Peroxisomal \beta-oxidation
- oxidation of a range of fatty acids including:
  1) very-long-chain fatty acids
     -  do not degrade fatty acids to completion
  2) pristanic acid
  3) the bile acid intermediates di- and trihydroxycholes-tanoic acid
  4) a range of eicosanoids

- Two acyl-CoA oxidases (ACOX1 & 2)
- Two bifunctional proteins (LBP & DBP)
- Two thiolases (ACAA1 & SCPx). 
- Single enzyme or transport protein defect result in abnormalities in some fatty acids.

** Peroxisomal \beta-oxidation Disorders
- Peroxisomal \beta-oxidation disorders can be subdivided into two groups:
  1) single peroxisomal enzyme or transport protein deficiencies
     - X-linked adrenoleukodystrophy (X-ALD)
  2) generalized peroxisomal beta-oxidation deficiencies.
     - Zellweger syndrome 

** X-linked Adrenoleukodystrophy


** Zellweger Spectrum Disorders
* Peroxisomal \alpha-oxidation Disorders 
** Adult Refsum Disease
* Sjogren Larsson Syndrome
** Test

* Very Long Chain Fatty Acid Measurement
https://adrenoleukodystrophy.info/mutations-biochemistry/vlcfa
The assay depends upon demonstration of increased levels of C26:0 and increases in the C26:0/C22:0 and C24:0/C22:0 ratios. The experience with this assay in more than 2,000 ALD patients (males and females) has demonstrated that approximately 10 to 20% of women with ALD have normal levels of VLCFA.
For women, a normal plasma VLCFA level thus does not exclude the diagnosis adrenoleukodystrophy. When a female is suspected to have adrenoleukodystrophy, mutation analysis is the most reliable method for the diagnosis. Ideally, the mutation in the family has to be defined in an affected male or obligate heterozygote relative (an obligate heterozygote is a woman either with a father diagnosed with adrenoleukodystrophy or a woman with two children with genetically proven adrenoleukodystrophy).

