#+TITLE: Laboratory Methods for Quantitative Acyl-Carnitines in Biological Matrices
#+AUTHOR: Matthew Henderson, PhD, FCACB
#+DATE: \today

:pPROPERTIES:
#+DRAWERS: PROPERTIES
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [presentation, smaller]
#+BEAMER_THEME: Hannover
#+BEAMER_COLOR_THEME: whale
#+BEAMER_FRAME_LEVEL: 2
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)
#+OPTIONS: H:2 toc:nil
#+PROPERTY: header-args:R :session *R*
#+PROPERTY: header-args :cache no
#+PROPERTY: header-args :tangle yes
#+STARTUP: beamer
#+STARTUP: overview
#+STARTUP: hidestars
#+STARTUP: indent
# #+BEAMER_HEADER: \subtitle{What is an Automated and Reproducible Report?}
#+BEAMER_HEADER: \institute[NSO]{Newborn Screening Ontario | The University of Ottawa}
#+BEAMER_HEADER: \titlegraphic{\includegraphics[height=1cm,keepaspectratio]{../logos/NSO_logo.pdf}\includegraphics[height=1cm,keepaspectratio]{../logos/cheo-logo.png} \includegraphics[height=1cm,keepaspectratio]{../logos/UOlogoBW.eps}}
#+latex_header: \hypersetup{colorlinks,linkcolor=white,urlcolor=blue}
#+LaTeX_header: \usepackage{textpos}
#+LaTeX_header: \usepackage{textgreek}
#+LaTeX_header: \usepackage[version=4]{mhchem}
#+LaTeX_header: \usepackage{chemfig}
#+LaTeX_header: \usepackage{siunitx}
#+LaTex_HEADER: \usepackage[usenames,dvipsnames]{xcolor}
#+LaTeX_HEADER: \usepackage[T1]{fontenc}
#+LaTeX_HEADER: \usepackage{lmodern}
#+LaTeX_HEADER: \usepackage{verbatim}
#+LaTeX_HEADER: \usepackage{tikz}
#+LaTeX_HEADER: \usetikzlibrary{shapes.geometric,arrows,decorations.pathmorphing,backgrounds,positioning,fit,petri}
:END:
#+BEGIN_LaTeX
%\logo{\includegraphics[width=1cm,height=1cm,keepaspectratio]{../logos/NSO_logo_small.pdf}~%
%    \includegraphics[width=1cm,height=1cm,keepaspectratio]{../logos/UOlogoBW.eps}%
%}

\vspace{220pt}
\beamertemplatenavigationsymbolsempty
\setbeamertemplate{caption}[numbered]
\setbeamerfont{caption}{size=\tiny}
% \addtobeamertemplate{frametitle}{}{%
% \begin{textblock*}{100mm}(.85\textwidth,-1cm)
% \includegraphics[height=1cm,width=2cm]{cat}
% \end{textblock*}}

\tikzstyle{chemical} = [rectangle, rounded corners, text width=5em, minimum height=1em,text centered, draw=black, fill=none]
\tikzstyle{hardware} = [rectangle, rounded corners, text width=5em, minimum height=1em,text centered, draw=black, fill=gray!30]
\tikzstyle{ms} = [rectangle, rounded corners, text width=5em, minimum height=1em,text centered, draw=orange, fill=none]
\tikzstyle{msw} = [rectangle, rounded corners, text width=7em, minimum height=1em,text centered, draw=orange, fill=none]
\tikzstyle{label} = [rectangle,text width=5em, minimum height=1em, text centered, draw=none, fill=none]
\tikzstyle{hl} = [rectangle, rounded corners, text width=5em, minimum height=1em,text centered, draw=black, fill=red!30]
\tikzstyle{arrow} = [thick,->,>=stealth]
\tikzstyle{hl-arrow} = [ultra thick,->,>=stealth,draw=red]

#+END_LaTeX

* Introduction

** Carnitine

- Carnitine (3-carboxy-2-hydroxy-N,N,N-tri-methylpropan-1-aminium) is
  an endogenous quaternary ammonium compound synthesized from lysine
  and methionine

- Primary function is to shuttle long chain fatty acids to the
  mitochondrial matrix, where they subsequently undergo
  \Beta{}-oxidation


#+BEGIN_LaTeX
\centering
\chemname{\chemfig[][scale=.33]{H3N-N^{+}([2]-CH3)([6]-CH3)-CH2-C([2]-H)([6]-O)-CH_2-C([1]=O)([7]-O^{-})}}{\tiny Carnitine}
\chemname{\chemfig[][scale=.33]{H3N-N^{+}([2]-CH3)([6]-CH3)-CH2-C([2]-H)([6]-O-C([0]=O)-{\color{red}R})-CH_2-C([1]=O)([7]-O^{-})}}{\tiny Acylcarnitine}
\chemname{\chemfig[][scale=.33]{H3N-N^{+}([2]-CH3)([6]-CH3)-CH2-C([2]-H)([6]-O-C([0]=O)-{\color{red}R})-CH_2-C([2]=O)-O-CH_2-CH_2-CH_2-CH_3}}{\tiny Acylcarnitine, butyl ester}

#+END_LaTeX
** Acyl-Carnitines Measurement
- Typically, carnitine is derivitized to from a butyl ester, thus
  improving its ionization and retention characteristics. A potential
  problem with this approach is that the acidic conditions used to
  carry out the reaction may hydrolyze other acyl esters, resulting in
  ex-vivo artifacts.

- Low carnitine levels can mask diagnostic elevations in plasma
  acylcarnitines.Therefore,interpretation of plasma acylcarnitines
  without evaluating the total carnitine pool can lead to
  misdiagnosis. Because many of the adverse effects of the described
  disorders may be mitigated through dietary intervention and
  supplementation, early diagnosis is critical. Thus accurate and
  robust methods for carnitine quantification are critical.

* FIA-MS/MS

** FIA-MS/MS sample 

- Amino acids in the DBS eluate are esterified as butyl esters with butanol-hydrogen chloride.

#+BEGIN_LaTeX
\centering
\schemedebug{false}
\schemestart
\chemname{\chemfig[][scale=.33]{{\color{red}R}-[::-60](<[::-60]NH_3^+)-[::60](=[::60]O)-[::-60]OH}}{\tiny \textalpha{}-amino acid}
\+
\chemname{\chemfig[][scale=.33]{HO-[::30]-[::-60]-[::60]-[::-60]}}{\tiny n-butanol}
\arrow{-U>[][{\tiny \ce{H2O}}]}
\chemname{\chemfig[][scale=.33]{{\color{red}R}-[::-60](<[::-60]NH_3^+)-[::60](=[::60]O)-[::-60]O-[::60]-[::-60]-[::60]-[::-60]}}{\tiny AA butyl ester}
\schemestop
#+END_LaTeX


- Solvent delivery is via HPLC with no chromatography, called flow injection analysis.
- 10 \micro{}L of sample extract is injected into a flowing stream operating at ~ 0.15 ml/min.

- Typical injection rates between samples are 2 min, giving a potential 400-
  to 600-sample capacity per instrument per day.
  - volume is typically 200-400 specimens per instrument per day
  - maintenance issues, repeat specimen analysis.
    
** FIA-MS/MS schematic
#+BEGIN_LaTeX
\begin{center}
\begin{tikzpicture}[node distance=7em]
% nodes
\node(ms1)[ms]{MS1: Mass Filter};
\node(cc)[ms, right of=ms1]{Collision cell};
\node(ms2)[ms, right of=cc]{MS2: Mass Filter};
\node(ion)[ms, below of=ms1,yshift=3em]{Ionization};
\node(lc)[msw, below of=ion,yshift=3em]{Injection};
\node(detector)[ms, below of=ms2, yshift=3em]{Detector};
% arrows
\draw[arrow](lc) -- (ion);
\draw[arrow](ion) -- (ms1);
\draw[arrow](ms1) -- (cc);
\draw[arrow](cc) -- (ms2);
\draw[arrow](ms2) -- (detector);
\end{tikzpicture}
\end{center}
#+END_LaTeX


** FIA-MS/MS transitions

- Electrospray ionization in positive mode
- \alpha{}-amino acids fragment to produce the neutral butyl formate molecule (102 Da). 
- A neutral loss scan is used to identify parent molecules with a NL of 102 Da.
- MRM is used to detected amino acids with basic functional groups
  - arginine, ornithine and citrulline

#+BEGIN_LaTeX
\centering
\schemedebug{false}
\schemestart
\chemname{\chemfig[][scale=.33]{{\color{red}R}-[::-60](<[::-60]NH_3^+)-[::60](=[::60]O)-[::-60]O-[::60]-[::-60]-[::60]-[::-60]}}{\tiny AA butyl ester}
\arrow{->[{\tiny fragmentation}]}
\chemname{\chemfig[][scale=.33]{{\color{red}R}-[::60]=NH_2^{+}}}{\tiny fragment}
\+
\chemname{\chemfig[][scale=.33]{H-[::60](=[::60]O)-[::-60]O-[::60]-[::-60]-[::60]-[::-60]}}{\tiny butyl formate (102 Da)}
\schemestop
#+END_LaTeX

** FIA-MS/MS  MRM

- Citrulline contains a labile amino group that fragments together with butyl formate.
- CID results in net neutral fragmentation of butyl formate (102 Da) plus \ce{NH3} (17 Da)
- [[https://en.wikipedia.org/wiki/Selected_reaction_monitoring][SRM]] Citrulline-Bu 232.15 Da \to 113 Da , loss of 119 Da  

#+BEGIN_LaTeX
\centering
\schemedebug{false}
\schemestart
\chemname{\chemfig[][scale=.33]{H_2N-[::30,,2,](=[::60]O)-[::-60]NH-[::60]-[::-60]-[::60]-[::-60](<[::-60]NH_3^+)-[::60](=[::60]O)-[::-60]OH}}{\tiny citrulline 175 Da}
\+
\chemname{\chemfig[][scale=.33]{HO-[::30]-[::-60]-[::60]-[::-60]}}{\tiny n-butanol 74 Da}
\arrow{-U>[][{\tiny \ce{H2O}}]}
\chemname{\chemfig[][scale=.33]{H_2N-[::30,,2,](=[::60]O)-[::-60]NH-[::60]-[::-60]-[::60]-[::-60](<[::-60]NH_3^+)-[::60](=[::60]O)-[::-60]O-[::60]-[::-60]-[::60]-[::-60]}}{\tiny 232 Da}
\schemestop
#+END_LaTeX



#+BEGIN_LaTeX
\centering
\schemedebug{false}
\schemestart
\chemname{\chemfig[][scale=.33]{H_2N-[::60]-[::-60]-[::60]-[::-60]-[::60]N=O=C}}{\tiny 113 Da}
\+
\chemname{\chemfig[][scale=.33]{H-[::60](=[::60]O)-[::-60]O-[::60]-[::-60]-[::60]-[::-60]}}{\tiny 102 Da}
\+
\chemname{\chemfig[][scale=.43]{NH_3}}{\tiny 17 Da}
\schemestop
#+END_LaTeX

- Its name is derived from citrullus, the Latin word for watermelon, from which it was first isolated in 1914 by Koga and Odake. 


** FIA-MS/MS Amino Acid Scan
*** Quantified Amino Acids
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
- Glycine
- Alanine
- Valine
- Leucine
- Methionine
- Phenylalanine
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
- Tyrosine
- Ornithine
- Citruline
- Arginine
- \color{blue}Succinylacetone


** Pros and Cons of FIA-MS/MS using DBS
- As compared to AAA and LC-MS/MS 
*** Pros
- ~ 2 min analysis time
- Analyte specificity
- Acylcarnitines quantified simultaneously

*** Cons
- Variability in DBS sample as described above
- Iso-baric compounds
  - leucine, Isoleucine, Alloisoleucine
- Fewer AA quantified
  - homocystine (free)
  - glutamine


* LC-MS/MS
** LC-MS/MS schematic
#+BEGIN_LaTeX
\begin{center}
\begin{tikzpicture}[node distance=7em]
% nodes
\node(ms1)[ms]{MS1: Mass Filter};
\node(cc)[ms, right of=ms1]{Collision cell};
\node(ms2)[ms, right of=cc]{MS2: Mass Filter};
\node(ion)[ms, below of=ms1,yshift=3em]{Ionization};
\node(lc)[msw, below of=ion,yshift=3em]{Chromatography};
\node(detector)[ms, below of=ms2, yshift=3em]{Detector};
% arrows
\draw[arrow](lc) -- (ion);
\draw[arrow](ion) -- (ms1);
\draw[arrow](ms1) -- (cc);
\draw[arrow](cc) -- (ms2);
\draw[arrow](ms2) -- (detector);
\end{tikzpicture}
\end{center}
#+END_LaTeX



** Inlet table                                                     :noexport:
#+tblname: data-table
| Time | Flow |   %A |   %B |
|------+------+------+------|
|    0 | 0.65 | 99.5 |  0.5 |
| 14.0 | 0.65 | 70.0 | 30.0 |
| 17.5 | 0.65 | 70.0 | 30.0 |
| 18.5 | 0.65 | 99.5 |  0.5 |
| 19.5 | 0.65 | 99.5 |  0.5 |
| 24.0 |  0.7 | 99.5 |  0.5 |
| 25.0 | 0.65 | 99.8 |  0.5 |

** LC-MS/MS sample prep
- 10 \micro{}L of sample is mixed with 990 \micro{}L of IS in 0.5 mM perfluoroheptanoic acid and centrifuge to deproteinize.
- 200 \micro{}L of supernatant is removed
- 7.5 \micro{}L is injected onto an octadecylsilyl (C18) stationary phase.


#+begin_src gnuplot :var data=data-table :file ./figures/outletmethod.pdf
reset
set title "UPLC Gradient"
set xlabel "min"

set xrange [0:26]

set ylabel "percent"
set yrange [0:100]

plot data u 1:3 w lp lw 2 title 'A', \
     data u 1:4 w lp lw 2 title 'B'

#+end_src

#+ATTR_LATEX: :width 0.7\textwidth
#+RESULTS:
[[file:./figures/outletmethod.pdf]]


** Ion-Pairing Chromatography

#+BEGIN_LaTeX
\centering
\chemfig[][scale=.70]{CF_3-{(CF_2)_4}-CF_2-[::30](=[::60]O)-[::-60]OH}

\vspace{3em}

\ce{AA+ + PFHA-  <=> AA+ PFHA-}
#+END_LaTeX


** LC- MS/MS transitions
- ESI in positive mode
  - MRM

*** Quantified amino acids
\scriptsize
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:
- phosphoserine
- taurine
- phosphoethanolamine
- aspartate
- hydroxyproline
- threonine
- serine
- asparagine
- glutamate
- glutamine
- sarcosine
- aminoadipic
- proline
- glycine

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:


- alanine
- citulline
- 2-aminobutyric
- valine
- cystine
- saccharopine
- methionine
- alloisoleucine
- cystathionine
- isoleucine
- leucine
- arginosuccinic acid
- tyrosine
- \beta{}-alanine

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:



- phenylalanine
- aminoisobutyric
- \gamma{}-aminobutryic
- ethanolamine
- hydroxylysine
- ornithine
- lysine
- 1-methylhistidine
- histidine
- tryptophan
- 3-methylhistidine
- anserine
- carnosine
- arginine
- s-sulfocyteine*




** Pros and Cons of LC-MS/MS
- As compared to FIA-MS/MS 
*** Pros
- 43 vs 11 amino acids quantified
  - Leu/Ile/Allo 
- Iso-baric compounds resolved
  - Leucine, Isoleucine, Alloisoleucine
*** Cons
- Too slow for NBS
- Manual peak integration


** Pros and Cons of LC-MS/MS
- As compared to AAA 
*** Pros
- ~ 30 min shorter analysis time
- Analyte specificity
  - Based on MRM rather than RT and ninhydrin reactivity
    - gentamycin, acetaminophen, dopamine analogs
  - Co-eluting substances cannot be separated and distinguished on a
    standard IEC chromatogram
    - Homocitrulline co-elutes with methionine
    - ASA co-elutes with leucine
    - Alloisoleucine co-elutes with cystathionine
    - Tryptophan co-elutes with histidine
- Long term reagent expense

*** Cons
- Upfront hardware expense
- Manual peak integration
- Lab developed test - not standardized
- Changing LOQ with equipment age 


