#+TITLE: Laboratory Methods for Quantitative Acyl-Carnitines in Biological Matrices
#+AUTHOR: Matthew Henderson, PhD, FCACB
#+DATE: \today

:PROPERTIES:
#+DRAWERS: PROPERTIES
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [presentation, smaller]
#+BEAMER_THEME: Hannover
#+BEAMER_COLOR_THEME: whale
#+BEAMER_FRAME_LEVEL: 2
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)
#+OPTIONS: H:2 toc:nil
#+PROPERTY: header-args:R :session *R*
#+PROPERTY: header-args :cache no
#+PROPERTY: header-args :tangle yes
#+STARTUP: beamer
#+STARTUP: overview
#+STARTUP: hidestars
#+STARTUP: indent
# #+BEAMER_HEADER: \subtitle{What is an Automated and Reproducible Report?}
#+BEAMER_HEADER: \institute[NSO]{Newborn Screening Ontario | The University of Ottawa}
#+BEAMER_HEADER: \titlegraphic{\includegraphics[height=1cm,keepaspectratio]{../logos/NSO_logo.pdf}\includegraphics[height=1cm,keepaspectratio]{../logos/cheo-logo.png} \includegraphics[height=1cm,keepaspectratio]{../logos/UOlogoBW.eps}}
#+latex_header: \hypersetup{colorlinks,linkcolor=white,urlcolor=blue}
#+LaTeX_header: \usepackage{textpos}
#+LaTeX_header: \usepackage{textgreek}
#+LaTeX_header: \usepackage[version=4]{mhchem}
#+LaTeX_header: \usepackage{chemfig}
#+LaTeX_header: \usepackage{siunitx}
#+LaTex_HEADER: \usepackage[usenames,dvipsnames]{xcolor}
#+LaTeX_HEADER: \usepackage[T1]{fontenc}
#+LaTeX_HEADER: \usepackage{lmodern}
#+LaTeX_HEADER: \usepackage{verbatim}
#+LaTeX_HEADER: \usepackage{tikz}
#+LaTeX_HEADER: \usetikzlibrary{shapes.geometric,arrows,decorations.pathmorphing,backgrounds,positioning,fit,petri}
:END:
#+BEGIN_LaTeX
%\logo{\includegraphics[width=1cm,height=1cm,keepaspectratio]{../logos/NSO_logo_small.pdf}~%
%    \includegraphics[width=1cm,height=1cm,keepaspectratio]{../logos/UOlogoBW.eps}%
%}

\vspace{220pt}
\beamertemplatenavigationsymbolsempty
\setbeamertemplate{caption}[numbered]
\setbeamerfont{caption}{size=\tiny}
% \addtobeamertemplate{frametitle}{}{%
% \begin{textblock*}{100mm}(.85\textwidth,-1cm)
% \includegraphics[height=1cm,width=2cm]{cat}
% \end{textblock*}}

\tikzstyle{chemical} = [rectangle, rounded corners, text width=5em, minimum height=1em,text centered, draw=black, fill=none]
\tikzstyle{hardware} = [rectangle, rounded corners, text width=5em, minimum height=1em,text centered, draw=black, fill=gray!30]
\tikzstyle{ms} = [rectangle, rounded corners, text width=5em, minimum height=1em,text centered, draw=orange, fill=none]
\tikzstyle{msw} = [rectangle, rounded corners, text width=7em, minimum height=1em,text centered, draw=orange, fill=none]
\tikzstyle{label} = [rectangle,text width=5em, minimum height=1em, text centered, draw=none, fill=none]
\tikzstyle{hl} = [rectangle, rounded corners, text width=5em, minimum height=1em,text centered, draw=black, fill=red!30]
\tikzstyle{arrow} = [thick,->,>=stealth]
\tikzstyle{hl-arrow} = [ultra thick,->,>=stealth,draw=red]

#+END_LaTeX

* Introduction
** Carnitine and Acylcarnitines

- Carnitine (3-hydroxy-4-N,N,N-trimethylaminobutyrate) is
  an endogenous quaternary ammonium compound synthesized from lysine
  and methionine.
- L-Carnitine has been described as a "conditionally essential"
  nutrient for humans.
- Population having a requirement for carnitine include:
  - infants (premature and full-term),
  - patients on long-term parenteral nutrition,
  - perhaps children.
- Exogenous carnitine is required to maintain "normal" (in the
  epidemiologic sense) plasma or serum carnitine concentrations in
  humans of all ages.
- Primary function is to shuttle long chain fatty acids to the
  mitochondrial matrix, for \Beta{}-oxidation.


#+BEGIN_LaTeX
\centering
\chemname{\chemfig[][scale=.33]{H3C-N^{+}([2]-CH3)([6]-CH3)-CH2-C([2]-H)([6]-OH)-CH_2-C([1]=O)([7]-O^{-})}}{\tiny Carnitine}
\hspace{3em}
\chemname{\chemfig[][scale=.33]{H3C-N^{+}([2]-CH3)([6]-CH3)-CH2-C([2]-H)([6]-O-C([0]=O)-{\color{red}R})-CH_2-C([1]=O)([7]-O^{-})}}{\tiny Acylcarnitine}
%\chemname{\chemfig[][scale=.33]{H3C-N^{+}([2]-CH3)([6]-CH3)-CH2-C([2]-H)([6]-O-C([0]=O)-{\color{red}R})-CH_2-C([2]=O)-O-CH_2-CH_2-CH_2-CH_3}}{\tiny Acylcarnitine, butyl ester}

#+END_LaTeX

** Sample Type

- Plasma
  - Diagnostic testing for FAODs and OAs
  - Monitoring
- Dried blood spot
  - Newborn Screening for FAODs and OAs
- Urine
  - Diagnosis of CUD


* FIA-MS/MS

** FIA-MS/MS sample 

- Acylcarnitines in the DBS eluate are esterified as butyl esters with butanol-hydrogen chloride.

#+BEGIN_LaTeX
\definesubmol{x}{-[1,.6]-[7,.6]}
\definesubmol{y}{-[7,.6]-[1,.6]}
\definesubmol{d}{!y!y-[7,.6]COOH}
\definesubmol{e}{!y!y}
\centering
\schemedebug{false}
\schemestart
\chemname{\chemfig[][scale=.33]{-N^{+}([2]-)([6]-)-[1]-[7]([6]-O-([5]=O)!e)-[1]-[7]([7]=O)([1]-O^{-})}}{\tiny C5-carnitine}
\+
\chemname{\chemfig[][scale=.33]{HO!x!x}}{\tiny n-butanol}
\arrow{-U>[][{\tiny \ce{H2O}}]}
\chemname{\chemfig[][scale=.33]{-N^{+}([2]-)([6]-)-[1]-[7]([6]-O-([5]=O)!e)-[1]-[7]([6]=O)-[1,.6]O!y!y}}{\tiny C5-carnitine, butyl ester}
\schemestop
\vspace{2em}
\schemedebug{false}
\schemestart
\chemname{\chemfig[][scale=.33]{-N^{+}([2]-)([6]-)-[1]-[7]([6]-O-([5]=O)!d)-[1]-[7]([7]=O)([1]-O^{-})}}{\tiny C6DC-carnitine}
\+
\chemname{\chemfig[][scale=.33]{HO!x!x}}{\tiny n-butanol}
\arrow{-U>[][{\tiny \ce{H2O}}]}
\chemname{\chemfig[][scale=.33]{-N^{+}([2]-)([6]-)-[1]-[7]([6]-O-([5]=O)!e-[7,.6]O!x!x)-[1]-[7]([6]=O)-[1,.6]O!y!y}}{\tiny C6DC-carnitine, butyl ester}
\schemestop 
#+END_LaTeX

** FIA-MS/MS schematic
#+BEGIN_LaTeX
\begin{center}
\begin{tikzpicture}[node distance=7em]
% nodespp
\node(ms1)[ms]{MS1: Mass Filter};
\node(cc)[ms, right of=ms1]{Collision cell};
\node(ms2)[ms, right of=cc]{MS2: Mass Filter};
\node(ion)[ms, below of=ms1,yshift=3em]{Ionization};
\node(lc)[msw, below of=ion,yshift=3em]{Injection};
\node(detector)[ms, below of=ms2, yshift=3em]{Detector};
% arrows
\draw[arrow](lc) -- (ion);
\draw[arrow](ion) -- (ms1);
\draw[arrow](ms1) -- (cc);
\draw[arrow](cc) -- (ms2);
\draw[arrow](ms2) -- (detector);
\end{tikzpicture}
\end{center}
#+END_LaTeX

- Solvent delivery is via HPLC with no chromatography, called flow injection analysis.
- 10 \micro{}L of sample extract is injected into a flowing stream operating at ~ 0.15 ml/min.

- Typical injection rates between samples are 2 min, giving a potential 400-
  to 600-sample capacity per instrument per day.
  - volume is typically 200-400 specimens per instrument per day
  - maintenance issues, repeat specimen analysis.
** FIA-MS/MS transitions

- Electrospray ionization in positive mode
- Parents of 85
- butylated acylcarnitines fragment to produce a characteristic ion with mass of 85 Da. 
- A parent ion scan is used to identify parent molecules with an 85 m/z fragment.

  



** Fragmentation
#+BEGIN_LaTeX
\definesubmol{x}{-[1,.6]-[7,.6]}
\centering
 \chemname{\chemfig[][scale=.33]{H_{3}C-N^{+}([2]-CH_3)([6]-CH_{3})-CH_2-C([2]-H)([6]-O-C([0]=O)-{\color{red}R})-CH_2-C([2]=O)-O-CH_2-CH_2-CH_2-CH_3}}{\tiny acylcarnitine, butyl ester}

\vspace{2.5em}

 \chemname{\chemfig[][scale=.33]{H_{3}C-N([1]-CH_3)([7]-CH_3)}}{\tiny trimethylamine}
\hspace{2em}
\chemname{\chemfig[][scale=.33]{{\color{red}R}-C([1]=O)([7]-OH)}}{\tiny carboxylic acid}
\hspace{2em}
 \chemname{\chemfig[][scale=.33]{H!x!x}}{\tiny butyl group}
\hspace{2em}
 \chemname{\chemfig[][scale=.33]{H_{2}C^{+}-HC=CH-C([1]=O)([7]-OH)}}{\tiny 85 m/z}
#+END_LaTeX

** MRM is used to detected dicarboxylic acylcarnitines

- MRMs are used for added sensitivity in selected Citrulline contains a labile amino group that fragments together with butyl formate.
- CID results in net neutral fragmentation of butyl formate (102 Da) plus \ce{NH3} (17 Da)
- [[https://en.wikipedia.org/wiki/Selected_reaction_monitoring][SRM]] for C0-Bu 218.1 Da \to 103 Da transition is optimal
- All others benefit from the added sensitivity of a SRM as compared to parent ion scan

\small
| Compound | Chan Reaction   |
|----------+-----------------|
| C0       | 218.10 > 103.00 |
| C0 IS    | 227.10 > 103.00 |
| C2       | 260.20 > 85.00  |
| C2 IS    | 263.20 > 85.00  |
| C3       | 274.20 > 85.00  |
| C3 IS    | 277.20 > 85.00  |
| C3DC     | 360.30 > 85.00  |
| C4DC     | 374.30 > 85.00  |
| C5DC     | 388.35 > 85.00  |
| C5DC IS  | 391.35 > 85.00  |
| C6DC     | 402.45 > 85.00  |
| C8DC     | 430.45 > 85.00  |

** FIA-MS/MS Acylcarnitine Scan
*** Quantified Acylcarnitines
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
- Glycine
- Alanine
- Valine
- Leucine
- Methionine
- Phenylalanine
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.5
:END:
- Tyrosine
- Ornithine
- Citruline
- Arginine
- \color{blue}Succinylacetone

C0
C2
C3
C3DC
C4
C4DC
C5
C5:1
C5DC
C5-OH
C6
C6DC
C8
C8:1
C10
C10:1
C12
C12:1
C14
C14:1
C14:2
C14-OH
C16
C16:1
C16:1-OH
C16-OH
C18
C18:1
C18:1-OH
C18:2
C18-OH
** Pros and Cons of FIA-MS/MS using DBS
- As compared to AAA and LC-MS/MS 
*** Pros
- ~2 min analysis time
- Analyte specificity
- Acylcarnitines quantified simultaneously

*** Cons
- Variability in DBS sample as described above
- Iso-baric compounds
  - leucine, Isoleucine, Alloisoleucine
- Fewer AA quantified
  - homocystine (free)
  - glutamine


* LC-MS/MS
** LC-MS/MS schematic
#+BEGIN_LaTeX
\begin{center}
\begin{tikzpicture}[node distance=7em]
% nodes
\node(ms1)[ms]{MS1: Mass Filter};
\node(cc)[ms, right of=ms1]{Collision cell};
\node(ms2)[ms, right of=cc]{MS2: Mass Filter};
\node(ion)[ms, below of=ms1,yshift=3em]{Ionization};
\node(lc)[msw, below of=ion,yshift=3em]{Chromatography};
\node(detector)[ms, below of=ms2, yshift=3em]{Detector};
% arrows
\draw[arrow](lc) -- (ion);
\draw[arrow](ion) -- (ms1);
\draw[arrow](ms1) -- (cc);
\draw[arrow](cc) -- (ms2);
\draw[arrow](ms2) -- (detector);
\end{tikzpicture}
\end{center}
#+END_LaTeX



** Inlet table                                                     :noexport:
#+tblname: data-table
| Time |  Flow |  %A | %B |
|------+-------+-----+----|
|    0 |  1.00 | 100 |  0 |
|  0.3 | 0.095 | 100 |  0 |
|  1.2 | 0.100 | 100 |  0 |
| 1.55 | 0.500 | 100 |  0 |
| 1.85 | 0.100 | 100 |  0 |
|  2.5 | 0.100 | 100 |  0 |

** LC-MS/MS sample prep
- 10 \micro{}L of sample is mixed with 990 \micro{}L of IS in 0.5 mM perfluoroheptanoic acid and centrifuge to deproteinize.
- 200 \micro{}L of supernatant is removed
- 7.5 \micro{}L is injected onto an octadecylsilyl (C18) stationary phase.


#+begin_src gnuplot :var data=data-table :file ./figures/outletmethod.pdf
reset
set title "UPLC Method"
set key off
set xlabel "min"

set xrange [0:3]

set ylabel "ml/min"
set yrange [0:1.2]

plot data u 1:2 w lp lw 2 

#+end_src

#+ATTR_LATEX: :width 0.7\textwidth
#+RESULTS:
[[file:./figures/outletmethod.pdf]]


** Ion-Pairing Chromatography

#+BEGIN_LaTeX
\centering
\chemfig[][scale=.70]{CF_3-{(CF_2)_4}-CF_2-[::30](=[::60]O)-[::-60]OH}

\vspace{3em}

\ce{AA+ + PFHA-  <=> AA+ PFHA-}
#+END_LaTeX


** LC- MS/MS transitions
- ESI in positive mode
  - MRM

*** Quantified amino acids
\scriptsize
****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:
- phosphoserine
- taurine
- phosphoethanolamine
- aspartate
- hydroxyproline
- threonine
- serine
- asparagine
- glutamate
- glutamine
- sarcosine
- aminoadipic
- proline
- glycine

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:


- alanine
- citulline
- 2-aminobutyric
- valine
- cystine
- saccharopine
- methionine
- alloisoleucine
- cystathionine
- isoleucine
- leucine
- arginosuccinic acid
- tyrosine
- \beta{}-alanine

****                                                               :BMCOL:
:PROPERTIES:
:BEAMER_col: 0.3
:END:



- phenylalanine
- aminoisobutyric
- \gamma{}-aminobutryic
- ethanolamine
- hydroxylysine
- ornithine
- lysine
- 1-methylhistidine
- histidine
- tryptophan
- 3-methylhistidine
- anserine
- carnosine
- arginine
- s-sulfocyteine*




** Pros and Cons of LC-MS/MS
- As compared to FIA-MS/MS 
*** Pros
- 43 vs 11 amino acids quantified
  - Leu/Ile/Allo 
- Iso-baric compounds resolved
  - Leucine, Isoleucine, Alloisoleucine
*** Cons
- Too slow for NBS
- Manual peak integration


** Pros and Cons of LC-MS/MS
- As compared to AAA 
*** Pros
- ~ 30 min shorter analysis time
- Analyte specificity
  - Based on MRM rather than RT and ninhydrin reactivity
    - gentamycin, acetaminophen, dopamine analogs
  - Co-eluting substances cannot be separated and distinguished on a
    standard IEC chromatogram
    - Homocitrulline co-elutes with methionine
    - ASA co-elutes with leucine
    - Alloisoleucine co-elutes with cystathionine
    - Tryptophan co-elutes with histidine
- Long term reagent expense

*** Cons
- Upfront hardware expense
- Manual peak integration
- Lab developed test - not standardized
- Changing LOQ with equipment age 



* Free and Total Carnitine                                         :noexport:
** Overestimation of Free Carnitine
- The butylation procedure tested involves heating the dried extract
  in 60 ul of anhydrous n-butanol-3 mol/L HCl at 65\degree{}C for  15 min. 
- Butylated acylcarnitines are converted to butylated carnitine in
  n-butanol-3 mol/L HCl. [fn:johnson]

| Acyl Carnitine | Half-life (min) |
|----------------+-----------------|
| C2             |              31 |
| C10            |             125 |
| C18            |             172 |

 
- NSO uses 60\degree{}C for 20 minutes.

- A sample with low free carnitine and high acetylcarnitine.
  - 30% of the acetylcarnitine as well as smaller amounts of higher
    molecular mass acylcarnitines are converted to carnitine and the
    low carnitine sample could appear to be normal.
- The free carnitine results obtained by this screening method on
  blood spots with high levels of acylcarnitines should therefore be
  used with caution.

[fn:johnson] Johnson, D. W. (1999). Inaccurate measurement of free
carnitine by the electrospray tandem mass spectrometry screening
method for blood spots. Journal of Inherited Metabolic Disease, 22(2),
201–202. 
