#+TITLE: Hinterland Who's Who: Mitochondria
#+AUTHOR: Matthew Henderson, PhD, FCACB
#+DATE: \today

:PROPERTIES:
#+DRAWERS: PROPERTIES
#+LaTeX_CLASS: beamer
#+LaTeX_CLASS_OPTIONS: [presentation, smaller]
#+BEAMER_THEME: Hannover
#+BEAMER_COLOR_THEME: whale
#+COLUMNS: %40ITEM %10BEAMER_env(Env) %9BEAMER_envargs(Env Args) %4BEAMER_col(Col) %10BEAMER_extra(Extra)
#+OPTIONS: H:2 toc:nil
#+PROPERTY: header-args:R :session *R*
#+PROPERTY: header-args :cache no
#+PROPERTY: header-args :tangle yes
#+STARTUP: beamer
#+STARTUP: overview
#+STARTUP: hidestars
#+STARTUP: indent
# #+BEAMER_HEADER: \subtitle{Part 1: Maple Syrup Urine Diseas}
#+BEAMER_HEADER: \institute[NSO]{Newborn Screening Ontario | The University of Ottawa}
#+BEAMER_HEADER: \titlegraphic{\includegraphics[height=1cm,keepaspectratio]{../logos/NSO_logo.pdf}\includegraphics[height=1cm,keepaspectratio]{../logos/cheo-logo.png} \includegraphics[height=1cm,keepaspectratio]{../logos/UOlogoBW.eps}}
#+latex_header: \hypersetup{colorlinks,linkcolor=white,urlcolor=blue}
#+LaTeX_header: \usepackage{textpos}
#+LaTeX_header: \usepackage{textgreek}
#+LaTeX_header: \usepackage[version=4]{mhchem}
#+LaTeX_header: \usepackage{chemfig}
#+LaTeX_header: \usepackage{siunitx}
#+LaTeX_header: \usepackage{gensymb}
#+LaTex_HEADER: \usepackage[usenames,dvipsnames]{xcolor}
#+LaTeX_HEADER: \usepackage[T1]{fontenc}
#+LaTeX_HEADER: \usepackage{lmodern}
#+LaTeX_HEADER: \usepackage{verbatim}
#+LaTeX_HEADER: \usepackage{tikz}
#+LaTeX_HEADER: \usetikzlibrary{shapes.geometric,arrows,decorations.pathmorphing,backgrounds,positioning,fit,petri}
:END:

#+BEGIN_EXPORT LaTeX
%\logo{\includegraphics[width=1cm,height=1cm,keepaspectratio]{../logos/NSO_logo_small.pdf}~%
%    \includegraphics[width=1cm,height=1cm,keepaspectratio]{../logos/UOlogoBW.eps}%
%}

\vspace{220pt}
\beamertemplatenavigationsymbolsempty
\setbeamertemplate{caption}[numbered]
\setbeamerfont{caption}{size=\tiny}
% \addtobeamertemplate{frametitle}{}{%
% \begin{textblock*}{100mm}(.85\textwidth,-1cm)
% \includegraphics[height=1cm,width=2cm]{cat}
% \end{textblock*}}

\tikzstyle{chemical} = [rectangle, rounded corners, text width=5em, minimum height=1em,text centered, draw=black, fill=none]
\tikzstyle{hardware} = [rectangle, rounded corners, text width=5em, minimum height=1em,text centered, draw=black, fill=gray!30]
\tikzstyle{ms} = [rectangle, rounded corners, text width=5em, minimum height=1em,text centered, draw=orange, fill=none]
\tikzstyle{msw} = [rectangle, rounded corners, text width=7em, minimum height=1em,text centered, draw=orange, fill=none]
\tikzstyle{label} = [rectangle,text width=8em, minimum height=1em, text centered, draw=none, fill=none]
\tikzstyle{hl} = [rectangle, rounded corners, text width=5em, minimum height=1em,text centered, draw=black, fill=red!30]
\tikzstyle{box} = [rectangle, rounded corners, text width=5em, minimum height=5em,text centered, draw=black, fill=none]
\tikzstyle{arrow} = [thick,->,>=stealth]
\tikzstyle{hl-arrow} = [ultra thick,->,>=stealth,draw=red]
#+END_EXPORT 


* Background
** Mitochondria
- A double-membrane-bound organelle found in most eukaryotic organisms
  - liver cells can have more than 2000.
  - red blood cells have no mitochondria

- The organelle is composed of an outer membrane, intermembrane
  space, and inner membrane with cristae and matrix.

- The mitochondrion has its own independent genome that shows
  substantial similarity to bacterial genomes

- Mitochondrial proteins (proteins transcribed from mt DNA)
  vary depending on the tissue and the species. In humans, 615
  distinct types of protein have been identified from cardiac
  mitochondria

** Maternal Inheritance
- Mitochondria and therefore the mitochondrial DNA, usually come from
  the egg only.
- The egg cell contains relatively few mitochondria
  - these mitochondria divide to populate the cells
- Sperm mitochondria enter the egg, but do not contribute genetic
  information to the embryo.
  - paternal mitochondria are marked with ubiquitin for destruction
    inside the embryo.
https://en.wikipedia.org/wiki/Heteroplasmy#/media/File:Mitochondrial_Bottleneck.png
** Heteroplasmy

- Heteroplasmy is the presence of more than one type of organellar
  genome (mitochondrial DNA or plastid DNA) within a cell or
  individual.

- It is an important factor in considering the severity of
  mitochondrial diseases.

- Most eukaryotic cells contain many hundreds of mitochondria with
  hundreds of copies of mitochondrial DNA, it is common for mutations
  to affect only some mitochondria, leaving most unaffected.

- Although detrimental scenarios are well-studied, heteroplasmy can
  also be beneficial. For example, centenarians show a higher than
  average degree of heteroplasmy.

- Microheteroplasmy is present in most individuals. This refers to
  hundreds of independent mutations in one organism, with each
  mutation found in about 1-2% of all mitochondrial genomes.

** Muller's Ratchet and the Mitochondrial Bottleneck

- Entities undergoing uniparental inheritance and with little to no
  recombination can be subject to "Muller's ratchet"
  - the inexorable accumulation of deleterious mutations until
    functionality is lost.
- mitochondria avoid this buildup through a developmental process
  known as the mtDNA bottleneck. 
  - Cell-level selection acts to remove those cells with more deleterious mtDNA
  
*** Fusion
- response to cellular stress
- enables genetic complementation
  - fusion of the mitochondria allows two mitochondrial genomes with
    different defects within the same organelle to encode what the
    other lacks.

** Replication 

- Mitochondria divide by binary fission, similar to bacterial cell division

- mammalian mitochondria replicate their DNA and divide mainly in response
  to the energy needs of the cell,rather than in phase with the cell cycle.
  - When the energy needs of a cell are high, mitochondria grow and
    divide.
  - When the energy use is low, mitochondria are destroyed
    or become inactive.

- mitochondria are apparently randomly distributed to the daughter
  cells during the division of the cytoplasm.


** Human Mitochondrial DNA

- The human mitochondrial genome is a circular DNA molecule of about
  16 kilobases.
- It encodes 37 genes: 13 for subunits of respiratory complexes I,
  III, IV and V,
- 22 for mitochondrial tRNA (for the 20 standard amino acids, plus an
  extra gene for leucine and serine)
- 2 for rRNA.
- One mitochondrion can contain two to ten copies of its DNA.

** Alternative genetic code

- The mitochondria of many eukaryotes, including most plants, use the
  standard code.

#+CAPTION[mito code]: Exceptions to the standard genetic code in mitochondria
#+NAME: tab:code 
| Organism         | Codon    | Standard   | Mitochondria |
|------------------+----------+------------+--------------|
| Mammals          | AGA, AGG | Arginine   | Stop codon   |
| Invertebrates    | AGA, AGG | Arginine   | Serine       |
| Fungi            | CUA      | Leucine    | Threonine    |
| All of the above | AUA      | Isoleucine | Methionine   |
|                  | UGA      | Stop codon | Tryptophan   |

- the AUA, AUC, and AUU codons are all allowable start codons.
- Some of these differences should be regarded as pseudo-changes in
  the genetic code due to the phenomenon of RNA editing, which is
  common in mitochondria. 


** Mitochondrial Disease
- Mitochondrial diseases are about 15% of the time caused by mutations
  in the mitochondrial DNA that affect mitochondrial function.
- Other mitochondrial diseases are caused by mutations in genes of the
  nuclear DNA, whose gene products are imported into the mitochondria
  as well as acquired mitochondrial conditions.

* Biochemical Functions Relevant to IMD   

** Pyruvate and the Tricyclic Acid Cycle
- one molecule of glucose breaks down into two molecules of pyruvate
- Pyruvate is converted into acetyl-coenzyme A, which is the main
  input for a series of reactions known as the Krebs cycle
- Pyruvate is also converted to oxaloacetate by an anaplerotic
  reaction, which replenishes Krebs cycle intermediates; also, the
  oxaloacetate is used for gluconeogenesis

https://en.wikipedia.org/wiki/Citric_acid_cycle#/media/File:Citric_acid_cycle_with_aconitate_2.svg

** Ketogenesis & Ketolysis
- Ketone bodies are produced mainly in the mitochondria of liver cells, and synthesis can occur in response to an unavailability of blood glucose, such as during fasting
https://en.wikipedia.org/wiki/Ketogenesis#/media/File:Ketogenesis.svg
** Electron Transport Chain
- Energy obtained through the transfer of electrons down the ETC is used to pump protons from the mitochondrial matrix into the intermembrane space
- creats an electrochemical proton gradient (\delta pH) across the IMM.
- largely responsible for the mitochondrial membrane potential (ΔΨM).
- allows ATP synthase to use the flow of H+ through the enzyme back into the matrix to generate ATP from ADP and Pi.
- Complex I (NADH coenzyme Q reductase) accepts electrons from the Krebs cycle electron carrier NADH
- passes them to CoQ (ubiquinone; labeled Q),
- CoQ also receives electrons from complex II (succinate dehydrogenase).
- CoQ passes electrons to complex III (cytochrome bc1 complex; labeled III), which passes them to cytochrome c (cyt c).
- Cyt c passes electrons to Complex IV (cytochrome c oxidase; labeled IV), which uses the electrons and hydrogen ions to reduce molecular oxygen to water. 
** Oxidative phosphorylation
#+BEGIN_SRC dot :file ./figures/etc.pdf :cmdline -Kdot -Tpdf
  digraph {
           // graph from left to right
           rankdir=LR;
           splines=true;
           node [shape=box];
           nadh [label="NADH+H", fillcolor=grey, style=filled]
           c1 [label="Complex I", fillcolor=steelblue3, style=filled]
           q [label="CoQ", fillcolor=red3, style=filled]    
           c3 [label="Complex III", fillcolor=steelblue3, style=filled]     
           cytc [label="Cytochrome C", fillcolor=red3, style=filled]     
           c4 [label="Complex IV", fillcolor=steelblue3, style=filled]     
           h2o [label="H2O", fillcolor=grey, style=filled]     
           c2 [label="Complex II", fillcolor=forestgreen, style=filled]     
           s [label="Succinate", fillcolor=grey, style=filled]     
           nadh -> c1
           c1 -> q 
           q -> c3 
           c3 -> cytc 	 
           cytc -> c4
           c4 -> h2o
           c2 -> q
           s -> c2

           }    
#+END_SRC

#+RESULTS:
[[file:./figures/etc.pdf]]

 The complete breakdown of glucose in the presence of oxygen is called cellular respiration. The last steps of this process occur in mitochondria. The reduced molecules NADH and FADH2 are generated by the Krebs cycle, glycolysis, and pyruvate processing. These molecules pass electrons to an electron transport chain, which uses the energy released to create a proton gradient across the inner mitochondrial membrane. ATP synthase then uses the energy stored in this gradient to make ATP. This process is called oxidative phosphorylation because it uses energy released by the oxidation of NADH and FADH2 to phospolyrize ADP into ATP. 
 
 - https://en.wikipedia.org/wiki/Electron_transport_chain#/media/File:ATP-Synthase.svg

** Other Biochemical Functions Relevant to IMD   

- Mitochondrial Fatty Acid Oxidation

- Urea Cycle

- Heme Biosynthesis
